#pragma once

#define WGNX_LWIP_MEM_SIZE (32U * 1024U)
#define WGNX_LWIP_UDP_PCBS 16U
#define WGNX_LWIP_TCP_PCBS 1U
#define WGNX_LWIP_TCP_SEGMENTS 8U
#define WGNX_LWIP_TCP_MSS 1380U
#define WGNX_LWIP_TCP_WINDOW (2U * WGNX_LWIP_TCP_MSS)
#define WGNX_LWIP_TCP_SEND_BUFFER (2U * WGNX_LWIP_TCP_MSS)
#define WGNX_LWIP_TCP_SEND_QUEUE 8U
#define WGNX_LWIP_SYS_TIMEOUTS 12U
#define WGNX_LWIP_REASSEMBLIES 4U
#define WGNX_LWIP_REASSEMBLY_PBUFS 8U
#define WGNX_LWIP_FRAGMENT_PBUFS 8U
#define WGNX_LWIP_PBUF_POOL_SIZE 24U
#define WGNX_LWIP_PBUF_POOL_BUFSIZE 1600U
