#pragma once

#define WGNX_LWIP_MEM_SIZE (32U * 1024U)
#define WGNX_LWIP_UDP_PCBS 16U
#define WGNX_LWIP_REASSEMBLIES 4U
#define WGNX_LWIP_REASSEMBLY_PBUFS 8U
#define WGNX_LWIP_FRAGMENT_PBUFS 8U
#define WGNX_LWIP_PBUF_POOL_SIZE 24U
#define WGNX_LWIP_PBUF_POOL_BUFSIZE 1600U
