#pragma once

#include "wgnx/lwip_budget.h"

#define NO_SYS 1
#define SYS_LIGHTWEIGHT_PROT 0
#define LWIP_TIMERS 1
#define LWIP_TIMERS_CUSTOM 0

#define MEM_ALIGNMENT 8
#define MEM_SIZE WGNX_LWIP_MEM_SIZE
#define MEMP_MEM_MALLOC 0
#define MEMP_NUM_PBUF WGNX_LWIP_REASSEMBLY_PBUFS
#define MEMP_NUM_UDP_PCB WGNX_LWIP_UDP_PCBS
#define MEMP_NUM_TCP_PCB WGNX_LWIP_TCP_PCBS
#define MEMP_NUM_TCP_SEG WGNX_LWIP_TCP_SEGMENTS
#define MEMP_NUM_REASSDATA WGNX_LWIP_REASSEMBLIES
#define MEMP_NUM_FRAG_PBUF WGNX_LWIP_FRAGMENT_PBUFS
#define MEMP_NUM_SYS_TIMEOUT WGNX_LWIP_SYS_TIMEOUTS
#define PBUF_POOL_SIZE WGNX_LWIP_PBUF_POOL_SIZE
#define PBUF_POOL_BUFSIZE WGNX_LWIP_PBUF_POOL_BUFSIZE

#define LWIP_IPV4 1
#define LWIP_IPV6 0
#define LWIP_UDP 1
#define LWIP_TCP 1
#define TCP_MSS WGNX_LWIP_TCP_MSS
#define TCP_WND WGNX_LWIP_TCP_WINDOW
#define TCP_SND_BUF WGNX_LWIP_TCP_SEND_BUFFER
#define TCP_SND_QUEUELEN WGNX_LWIP_TCP_SEND_QUEUE
#define TCP_QUEUE_OOSEQ 0
#define LWIP_RAW 0
#define LWIP_ICMP 0
#define LWIP_ARP 0
#define LWIP_ETHERNET 0
#define LWIP_IGMP 0
#define LWIP_DHCP 0
#define LWIP_DNS 0
#define LWIP_AUTOIP 0
#define LWIP_NETCONN 0
#define LWIP_SOCKET 0
#define LWIP_ALTCP 0
#define LWIP_NETIF_API 0
#define LWIP_NETIF_STATUS_CALLBACK 0
#define LWIP_NETIF_LINK_CALLBACK 0
#define LWIP_SINGLE_NETIF 1
#define IP_FORWARD 0
#define IP_OPTIONS_ALLOWED 0
#define IP_FRAG 1
#define IP_REASSEMBLY 1
#define IP_REASS_MAX_PBUFS WGNX_LWIP_REASSEMBLY_PBUFS
#define IP_REASS_FREE_OLDEST 0

#define LWIP_STATS 1
#define LWIP_STATS_DISPLAY 0
#define LWIP_DEBUG 0
#define CHECKSUM_GEN_IP 1
#define CHECKSUM_GEN_UDP 1
#define CHECKSUM_CHECK_IP 1
#define CHECKSUM_CHECK_UDP 1
